check user permissions before kubectl apply

diff --git a/.github/workflows/k8s-apply-sub.yaml b/.github/workflows/k8s-apply-sub.yaml
--- a/.github/workflows/k8s-apply-sub.yaml
+++ b/.github/workflows/k8s-apply-sub.yaml
@@ -25,6 +25,39 @@ env:
   SCRIPTS_FOLDER: "./interop-infra-commons/scripts/helm"
 
 jobs:
+  initChecks:
+    runs-on: ubuntu-22.04
+    environment: ${{ inputs.environment }}
+    steps:
+      - name: Check user is a ${{ vars.ALLOWED_DEPLOY_GH_TEAM }} team member
+        id: checkUserPermissions
+        if: ${{ inputs.environment != 'dev' }}
+        env:
+            GITHUB_TOKEN: ${{ secrets.BOT_TEAMS_RO_PAT }}
+            ORG: ${{ github.repository_owner }}
+            TEAM: ${{ vars.ALLOWED_DEPLOY_GH_TEAM }}
+            USER: ${{ github.triggering_actor	}}
+        run: |
+          set -euo pipefail
+
+          set +e
+          # Check current user membership with gh api
+          GH_TEAM_MEMBERSHIP_RESPONSE=$(gh api -i --method GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \/orgs/$ORG/teams/$TEAM/memberships/$USER)
+          set -e
+          
+          # Extract the HTTP status code
+          HTTP_CODE=$(echo $GH_TEAM_MEMBERSHIP_RESPONSE | head -n 1 | cut -d' ' -f 2)
+
+          if [[ $HTTP_CODE -eq 404 ]]; then
+            echo "::error:: Resource not found. Please check the organization ($ORG), team ($TEAM), and user names ($USER). $USER is not memeber of specified team."
+            exit 1
+          elif [[ $HTTP_CODE -ne 200 ]]; then
+            echo "::error:: API response status code $HTTP_CODE."
+            echo $GH_TEAM_MEMBERSHIP_RESPONSE | tail -n 1 | jq -r .
+            exit 1
+          fi
+
+          echo "$USER has the correct permissions to execute the workflow."
   workflow_setup:
     name: Setup steps
     runs-on: [ self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}" ]
