feat(workflows): optional force deployment restart (#52)
Co-authored-by: Michele De Simone <106953981+micdes-pagopa@users.noreply.github.com>

diff --git a/.github/workflows/k8s-apply-sub.yaml b/.github/workflows/k8s-apply-sub.yaml
--- a/.github/workflows/k8s-apply-sub.yaml
+++ b/.github/workflows/k8s-apply-sub.yaml
@@ -148,41 +148,52 @@ jobs:
           MICROSERVICE_NAME: ${{ matrix.microservice }}
           K8S_NAMESPACE: ${{ inputs.environment }}
           TIMEOUT_SECONDS: ${{ inputs.timeout_seconds }}
+          FORCE_ROLLOUT: ${{ inputs.force_restart }}
+          
         run: |
           set -euo pipefail
 
+          #!/bin/sh
+          TIMEOUT="${TIMEOUT_SECONDS}s"
+          # Check if a rollout is in progress
+          echo "INFO - Verifying no active rollouts; waiting up to $TIMEOUT if required"
+          if ! kubectl rollout status -n "$K8S_NAMESPACE" "deployment/$MICROSERVICE_NAME" --timeout="$TIMEOUT" --watch >/dev/null 2>&1; then
+            echo "::error::ERROR - A rollout is already in progress for $MICROSERVICE_NAME in namespace $K8S_NAMESPACE"
+            exit 1
+          fi
+          
           export PROJECT_DIR=$(pwd)
           $SCRIPTS_FOLDER/kubectlApply-svc-single-standalone.sh --debug --environment $K8S_NAMESPACE -m $MICROSERVICE_NAME --output console 
 
-          CURRENT_SVC=$(kubectl get deployments -n $K8S_NAMESPACE | awk '{if (NR!=1) print $1}' | grep -v grep | grep -i $MICROSERVICE_NAME) 
-          
-          MAX_WAIT_TIME_SECONDS=$TIMEOUT_SECONDS
-          CYCLE_SLEEP_SECONDS=5
-          
-          CURRENT_DATE_SECONDS=$(date +%s)
-          WAIT_EXP_SECONDS=$(($CURRENT_DATE_SECONDS + $MAX_WAIT_TIME_SECONDS))
-          SVC_ROLLOUT_STATUS=1
+          echo "INFO - Apply changes for $MICROSERVICE_NAME."
+          "$SCRIPTS_FOLDER/kubectlApply-svc-single-standalone.sh" --debug --environment "$K8S_NAMESPACE -m $MICROSERVICE_NAME" --output console
+          sleep 5
 
-          while [[ $CURRENT_DATE_SECONDS -lt $WAIT_EXP_SECONDS ]]
-          do
-            set +e
-            kubectl rollout status -n $K8S_NAMESPACE deployment/$CURRENT_SVC > /dev/null
-            SVC_ROLLOUT_STATUS=$?
-            set -e
-            
-            if [[ $SVC_ROLLOUT_STATUS  -eq 0 ]]; then
-              echo "INFO -" $CURRENT_SVC "deployed"
-              break
+          DESIRED_REPLICAS=$(kubectl get deployment "$MICROSERVICE_NAME" -n "$K8S_NAMESPACE" -o jsonpath='{.spec.replicas}')
+          echo "INFO - Desired replicas: $DESIRED_REPLICAS"
+          if [ "$DESIRED_REPLICAS" -eq 0 ]; then
+            echo "::info::INFO - Desired replicas for $MICROSERVICE_NAME are 0. Stopping further operations."
+            exit 0
+          fi
+
+          # Check if the force rollout flag is true
+          if [ "$FORCE_ROLLOUT" = true ]; then
+            echo "::info::INFO - Force rollout restart requested $MICROSERVICE_NAME." 
+            if ! kubectl rollout status -n "$K8S_NAMESPACE" "deployment/$MICROSERVICE_NAME" --watch=false >/dev/null 2>&1; then
+              echo "::info::INFO - Rollout alredy active for $MICROSERVICE_NAME. No force restart needed."
             else
-              echo  "::warning::WARNING - " $CURRENT_SVC  "not yet deployed"
+              echo "INFO - No rollout in progress, forcing a rollout restart."
+              kubectl rollout restart -n "$K8S_NAMESPACE" "deployment/$MICROSERVICE_NAME"
             fi
+          fi 
+          
+          echo "INFO - Wait for the rollout of the $MICROSERVICE_NAME to finish (Max $TIMEOUT)."
+          if ! kubectl rollout status -n "$K8S_NAMESPACE" "deployment/$MICROSERVICE_NAME" --timeout="$TIMEOUT" --watch >/dev/null 2>&1; then
+            echo "::error::ERROR - Rollout for $MICROSERVICE_NAME failed or exceeded $TIMEOUT."
+            exit 1
+          fi
+          echo "INFO - Rollout for $MICROSERVICE_NAME completed successfully."
             
-            sleep $CYCLE_SLEEP_SECONDS
-            CURRENT_DATE_SECONDS=$(date +%s)
-          done
-
-          exit $SVC_ROLLOUT_STATUS
-
   deploy_cj:
     name: ${{ matrix.cronjob }}
     runs-on: [ self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}" ]
