Add the check of the cluster

diff --git a/.github/workflows/k8s-apply-sub.yaml b/.github/workflows/k8s-apply-sub.yaml
--- a/.github/workflows/k8s-apply-sub.yaml
+++ b/.github/workflows/k8s-apply-sub.yaml
@@ -112,6 +112,12 @@ jobs:
             exit 1
           fi
 
+          # Controllo se il cluster è raggiungibile
+          if ! kubectl cluster-info &> /dev/null; then
+            echo "::error::ERROR - Il cluster Kubernetes non è raggiungibile"
+            exit 1
+          fi
+
           # Controllo se c'è già un rollout in corso
           ROLLOUT_IN_PROGRESS=$(kubectl get rollout -n $K8S_NAMESPACE | grep -i $MICROSERVICE_NAME | grep -v "completed" | wc -l)
           if [[ $ROLLOUT_IN_PROGRESS -ne 0 ]]; then
